### ISSUE TITLE
جدیدا pytse کار نمی کنه

### ISSUE THREAD

**Issue by mrn3dmax** [Glyphack/pytse-client#125]
**توضیح مشکل پیش آمده**
سلام
ممنون از پکیجی که ارائه کردید
من قبلا با این پکیج کار می کردم و مشکلی نداشت
وقتی تمپ برنامه ها را پاک کردم پکیج های نصب شده روی پایتون از بین رفت
وقتی دوباره پکیج ها را نصب کردم پکیج شما کار نمی کنه

**چطور اتفاق افتاد؟**
تمپ ها را پاک کردم و در نصب جدید کار نمی کنه

**انتظار دارید چه اتفاقی بیوفته**

**اسکرین شات**
![image](https://user-images.githubusercontent.com/91030127/133940397-4eff43e6-343e-4411-a5fd-7101cfb61563.png)

**اطلاعات سیستم:**
 - سیستم عامل: مثل ویندوز ۱۰ 
 - 3.8 - ورژن پایتون
 - محیطی که توش کار میکردید( پایچارم)

**اطلاعات اضافی**
اروری که بعد از اجرای دستور زیر میاد:
import pytse_client as tse

ارور:
Traceback (most recent call last):
  File "C:/Users/mohsen/PycharmProjects/mypy/venv/mymodules/test.py", line 1, in <module>
    import pytse_client as tse
  File "C:\Users\mohsen\AppData\Roaming\Python\Python38\site-packages\pytse_client\__init__.py", line 1, in <module>
    from .download import download
  File "C:\Users\mohsen\AppData\Roaming\Python\Python38\site-packages\pytse_client\download.py", line 6, in <module>
    import pandas as pd
  File "C:\Users\mohsen\AppData\Roaming\Python\Python38\site-packages\pandas\__init__.py", line 11, in <module>
    __import__(dependency)
  File "C:\Users\mohsen\AppData\Roaming\Python\Python38\site-packages\numpy\__init__.py", line 148, in <module>
    from . import _distributor_init
  File "C:\Users\mohsen\AppData\Roaming\Python\Python38\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

ممنون می شم اگر جواب را به ایمیل بنده بدید
چون خیلی با گیت هاب کار نمی کنم
mohsen_rahmatI_nia@yahoo.com

**Comment by Glyphack** [comment]
سلام این مشکل از سمت نامپای هست که یکی از پکیج‌های مورد نیاز هست ممکنه به خاطر ورژن پایتون یا کامل نصب نشدن پایتون یا دلایل دیگه‌ای به مشکل خورده باشه این پکیج. برای حل مشکل یه پروژه دیگه بسازید و فقط پکیج
pandas رو نصب  کنید
ببینید کار میکنه یا اروری داره

**Comment by Glyphack** [comment]
به خاطر عدم فعالیت میبندم
