### ISSUE TITLE
مشکل در دانلود و فراخوانی دیتا

### ISSUE THREAD

**Issue by haameed7** [Glyphack/pytse-client#136]
tickers = tse.download(symbols="all",write_to_csv=True, include_jdate=True)
در نسخه جدید 
tse.download 
نمادها را دانلود میکند. ولی موقع فراخوانی ارور میدهد

** با دانگرید به نسخه قبلی مشکل رفع میشود

**Comment by haameed7** [comment]
MacOS
python 3.8.11

<img width="687" alt="Screen Shot 2021-10-18 at 16 34 17" src="https://user-images.githubusercontent.com/43357371/137736578-d4bf0c5a-4908-439e-9e5d-ae5ccdae6d34.png">
<img width="536" alt="Screen Shot 2021-10-18 at 16 35 28" src="https://user-images.githubusercontent.com/43357371/137736715-25c16bd1-3797-439e-acb8-aeb779ae01e1.png">

**Comment by Glyphack** [comment]
این ایشو رو تغییر میدم به اینکه نماد اوراق مشارکت ایران خودرو رو بتونیم درست بگیریم

**Comment by mostafa2msh** [comment]
سلام خسته نباشید ممنون میشم این مشکل رو هم حل کنید. زمانی که روی هاست یک سهام فراخوانی می کنم این خطا رو میده

Extra data: line 10254 column 2 (char 217578)
Traceback (most recent call last):
  File "/home/optionto/virtualenv/bot/3.9/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/optionto/bot/plugins/send_file.py", line 119, in main
    tse.download(symbols=text)
  File "/home/optionto/bot/pytse_client/download.py", line 42, in download
    ticker_index = _handle_ticker_index(symbol)
  File "/home/optionto/bot/pytse_client/download.py", line 264, in _handle_ticker_index
    ticker_index = symbols_data.get_ticker_index(symbol)
  File "/home/optionto/bot/pytse_client/symbols_data.py", line 21, in get_ticker_index
    return symbols_information().get(ticker_symbol, {}).get("index")
  File "/home/optionto/bot/pytse_client/symbols_data.py", line 16, in symbols_information
    ticker_name_to_index_mapping = json.load(symbols_name)
  File "/opt/alt/python39/lib64/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/alt/python39/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/alt/python39/lib64/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 10254 column 2 (char 217578)

**Comment by alised** [comment]
> raise JSONDecodeError("Extra data", s, end)

سلام 
لطفا مشکل خود را در یک پست مجزا مطرح کنید.
کدی هم که منجر به ایجاد خطا میشود کامل درج کنید.
