### ISSUE TITLE
خطای جزئیات حقیقی/ حقوقی

### ISSUE THREAD

**Issue by bhralzz** [Glyphack/pytse-client#93]
هنگام دانلود جزئیات حقیقی/حقوقی خطا می دهد

در زمان استفاده از کد زیر خطا ریپورت می کنه:
tse.download_client_types_records("all")

ValueError: 13 columns passed, passed data had 1 columns

سیستم  عامل ویندوز 10

**Comment by Glyphack** [comment]
ممنون این اتفاق همیشه میوفته؟ اگر هنوزم میوفته میشه مقدار بیشتری از ارور رو بفرستید؟

**Comment by bhralzz** [comment]
با تشکر از پاسختان

بله تکرار میشه هر دفعه تست می کنم
البته برای تک سهم درست کار می کنه! 
احتمالا دیتافریم یکی از نمادها رو نمی تونه تشکیل بده
متن خطا در ادامه آورده شده است

Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\envs\A1\lib\site-packages\pandas\core\internals\construction.py", line 568, in _list_to_arrays
    columns = _validate_or_indexify_columns(content, columns)

  File "C:\ProgramData\Anaconda3\envs\A1\lib\site-packages\pandas\core\internals\construction.py", line 692, in _validate_or_indexify_columns
    raise AssertionError(

AssertionError: 13 columns passed, passed data had 1 columns


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "d:\projects\stk\36_4000128\temp_test.py", line 5, in <module>
    records_dict = download_client_types_records("all")

  File "C:\ProgramData\Anaconda3\envs\A1\lib\site-packages\pytse_client\download.py", line 99, in download_client_types_records
    df: pd.DataFrame = future.result()

  File "C:\ProgramData\Anaconda3\envs\A1\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()

  File "C:\ProgramData\Anaconda3\envs\A1\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception

  File "C:\ProgramData\Anaconda3\envs\A1\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)

  File "C:\ProgramData\Anaconda3\envs\A1\lib\site-packages\pytse_client\download.py", line 119, in download_ticker_client_types_record
    client_types_data_frame = pd.DataFrame(data, columns=[

  File "C:\ProgramData\Anaconda3\envs\A1\lib\site-packages\pandas\core\frame.py", line 570, in __init__
    arrays, columns = to_arrays(data, columns, dtype=dtype)

  File "C:\ProgramData\Anaconda3\envs\A1\lib\site-packages\pandas\core\internals\construction.py", line 528, in to_arrays
    return _list_to_arrays(data, columns, coerce_float=coerce_float, dtype=dtype)

  File "C:\ProgramData\Anaconda3\envs\A1\lib\site-packages\pandas\core\internals\construction.py", line 571, in _list_to_arrays
    raise ValueError(e) from e

ValueError: 13 columns passed, passed data had 1 columns

**Comment by Glyphack** [comment]
من این تست رو تست‌ها اضافه کردم و مشکلی وجود نداشت در صورتی که باز رخ بده توی تست‌ها باید دیده بشه.
